kernel: locking/spinlock: store data as NonNull
Similarly to commit db85f1f9db46 ("locking/rwlock: store NonNull in
lock guards"), store the data in a spinlock guard as a NonNull. This
simplifies the future implementation of map() on the type.

While we are at it, impement Send and Sync for the guard type, as
otherwise the build for some fuzzers will be broken:

error[E0277]: `std::ptr::NonNull<()>` cannot be shared between threads safely
    --> fuzz/fuzz_targets/fs.rs:67:13
     |
67   | static MEM: OnceLock<TestRootMem<'_>> = OnceLock::new();
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^ `std::ptr::NonNull<()>` cannot be shared between threads safely
     |

Signed-off-by: Carlos López <clopez@suse.de>